/**
 * IST 1947 — Complete Authentic Product Catalogue
 * Sourced directly from IST 1947 official catalog
 */
export const PRODUCTS = [
  {
    "id": 8665237029047,
    "title": "2026",
    "handle": "2026",
    "collection": "Vijay",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "A limited-edition horological tribute commemorating iconic nights of Indian cricketing victory.",
    "editorialBlurb": "Defending the crown with ruthless composure. A tribute to the night India turned belief into an unshakeable sporting dynasty.",
    "description": "<p style=\"background: white;\"><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\">The night victory became a legacy.</span></p>\n\n<p style=\"background: white;\"><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\">Drawn from the deep navy and fresh blue of the most recent campaign, 2026 captures a win that felt less like an arrival and more like confirmation. After the release of 2024, this was India returning under the weight of expectation and still playing like a team in control - defending the crown, owning the moment, and turning a great era into something larger.</span></p>\n\n<p style=\"background: white;\"><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\">The cooler palette gives the watch a cleaner, more composed energy, confidence without the need to shout. 2026 is a tribute to the night India did not just win again. It defended, repeated, and turned belief into dynasty.</span></p>\n\n<p style=\"background: white;\"><b><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">2026 is a limited edition of 100 pieces only.</span></b></p>\n",
    "specs": {
      "caseSize": "43 mm",
      "thickness": "12.8 mm",
      "lugToLug": "50 mm",
      "lugWidth": "22 mm",
      "movement": "Miyota 82S7 Automatic Mechanical, 21,600 vph, 48-Hour Power Reserve, 21 Jewels",
      "crystal": "Domed Sapphire Crystal with multi-layer interior anti-reflective coating",
      "waterResistance": "5 ATM (50 Meters / 165 Feet)",
      "dial": "Forged carbon fiber & brushed multi-level dial with bat-and-ball small seconds at 5H & 24H AM/PM disc at 9H",
      "strap": "High-durability textured FKM rubber & performance sailcloth hybrid strap with deployant buckle",
      "caseMaterial": "316L Stainless Steel with PVD gunmetal matte finish & chamfered lugs",
      "caseback": "Exhibition sapphire crystal caseback revealing decorated automatic rotor & numbered edition engraving"
    },
    "images": [
      "assets/images/2026_1.jpg",
      "assets/images/2026_2.jpg",
      "assets/images/2026_3.jpg"
    ],
    "limitedEdition": true,
    "editionCount": 100,
    "colorAccent": "#A94B2C",
    "tags": [
      "2026",
      "Automatic Watch",
      "Carbon Fiber Dial",
      "Cricket Watch",
      "Dark Blue Strap",
      "Dark Blue Strap Watch",
      "Grey Dial",
      "Small Seconds",
      "Sports Watch",
      "Vijay",
      "Watches"
    ]
  },
  {
    "id": 8665236930743,
    "title": "2024",
    "handle": "2024",
    "collection": "Vijay",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "A limited-edition horological tribute commemorating iconic nights of Indian cricketing victory.",
    "editorialBlurb": "Bridgetown, 29 June 2024. Tears of triumph after a decade of heartbreaks. A masterclass in nerves and grit in the Caribbean dusk.",
    "description": "<p style=\"background: white;\"><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\">The night India exhaled.</span></p>\n\n<p style=\"background: white;\"><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\">Drawn from the blue and orange of modern Indian Cricket, 2024 captures the release of a victory that felt urgent, emotional, and long overdue. After years of coming close, the wait finally broke. The palette carries the energy of the era: intense, fearless, and impossible to look away from.</span></p>\n\n<p style=\"margin-bottom: 0cm; background: white;\"><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\">More than a celebration of winning, 2024 is about pressure survived, belief repaid, and a final that reminded everyone why cricket still has the power to stop time.</span></p>\n\n<p style=\"margin-bottom: 0cm; background: white;\"><b><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">2024 is a limited edition of 100 pieces only.</span></b></p>\n",
    "specs": {
      "caseSize": "43 mm",
      "thickness": "12.8 mm",
      "lugToLug": "50 mm",
      "lugWidth": "22 mm",
      "movement": "Miyota 82S7 Automatic Mechanical, 21,600 vph, 48-Hour Power Reserve, 21 Jewels",
      "crystal": "Domed Sapphire Crystal with multi-layer interior anti-reflective coating",
      "waterResistance": "5 ATM (50 Meters / 165 Feet)",
      "dial": "Forged carbon fiber & brushed multi-level dial with bat-and-ball small seconds at 5H & 24H AM/PM disc at 9H",
      "strap": "High-durability textured FKM rubber & performance sailcloth hybrid strap with deployant buckle",
      "caseMaterial": "316L Stainless Steel with PVD gunmetal matte finish & chamfered lugs",
      "caseback": "Exhibition sapphire crystal caseback revealing decorated automatic rotor & numbered edition engraving"
    },
    "images": [
      "assets/images/2024_1.jpg",
      "assets/images/2024_2.jpg",
      "assets/images/2024_3.jpg"
    ],
    "limitedEdition": true,
    "editionCount": 100,
    "colorAccent": "#A94B2C",
    "tags": [
      "2024",
      "Automatic Watch",
      "Carbon Fiber Dial",
      "Cricket Watch",
      "Grey Dial",
      "Orange Strap",
      "Orange Strap Watch",
      "Small Seconds",
      "Sports Watch",
      "Vijay",
      "Watches"
    ]
  },
  {
    "id": 8665236897975,
    "title": "2011",
    "handle": "2011",
    "collection": "Vijay",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "A limited-edition horological tribute commemorating iconic nights of Indian cricketing victory.",
    "editorialBlurb": "Wankhede Stadium, 2 April 2011. Twenty-eight years of longing crowned by a six into the Mumbai night. Deep navy victory finish.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">The night the wait finally ended.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">Drawn from the blue and orange of that unforgettable campaign, 2011 carries the weight of a victory that meant more because of where it happened and how long it had been coming. Every detail speaks to a night that was emotional, pressurised, and impossible to forget - a captain\u2019s six into the Mumbai sky, a master finally lifted on the shoulders of his team.\u00a0</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">2011 is not just a winning year. It is the year a generation got the ending it had been dreaming of!<b></b></span></p>\n\n<p><b><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">2011 is a limited edition of 100 pieces only.</span></b></p>\n",
    "specs": {
      "caseSize": "43 mm",
      "thickness": "12.8 mm",
      "lugToLug": "50 mm",
      "lugWidth": "22 mm",
      "movement": "Miyota 82S7 Automatic Mechanical, 21,600 vph, 48-Hour Power Reserve, 21 Jewels",
      "crystal": "Domed Sapphire Crystal with multi-layer interior anti-reflective coating",
      "waterResistance": "5 ATM (50 Meters / 165 Feet)",
      "dial": "Forged carbon fiber & brushed multi-level dial with bat-and-ball small seconds at 5H & 24H AM/PM disc at 9H",
      "strap": "High-durability textured FKM rubber & performance sailcloth hybrid strap with deployant buckle",
      "caseMaterial": "316L Stainless Steel with PVD gunmetal matte finish & chamfered lugs",
      "caseback": "Exhibition sapphire crystal caseback revealing decorated automatic rotor & numbered edition engraving"
    },
    "images": [
      "assets/images/2011_1.jpg",
      "assets/images/2011_2.jpg",
      "assets/images/2011_3.jpg"
    ],
    "limitedEdition": true,
    "editionCount": 100,
    "colorAccent": "#A94B2C",
    "tags": [
      "2011",
      "Automatic Watch",
      "Carbon Fiber Dial",
      "Cricket Watch",
      "Dark Blue Strap",
      "Dark Blue Strap Watch",
      "Grey Dial",
      "Small Seconds",
      "Sports Watch",
      "Vijay",
      "Watches"
    ]
  },
  {
    "id": 8665236865207,
    "title": "2007",
    "handle": "2007",
    "collection": "Vijay",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "A limited-edition horological tribute commemorating iconic nights of Indian cricketing victory.",
    "editorialBlurb": "Johannesburg, 24 September 2007. The young fearless squad that ignited a revolution in the global game under the Highveld lights.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">The night we found a new kind of swagger.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">Drawn from the light blue and bold yellow of that era, 2007 captures a moment that felt young, unexpected, and completely electric. This was not just a victory - it was the beginning of a new chapter: a team playing with freedom, instinct, and nerve in a format that brought a different kind of pressure and a different kind of joy.\u00a0</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">The bright colour accents give the watch a more playful, high-energy character. 2007 is a tribute to the win that announced a new generation: fearless, fast, and impossible to ignore.</span></p>\n\n<p><b><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">2007 is a limited edition of 100 pieces only.</span></b></p>\n",
    "specs": {
      "caseSize": "43 mm",
      "thickness": "12.8 mm",
      "lugToLug": "50 mm",
      "lugWidth": "22 mm",
      "movement": "Miyota 82S7 Automatic Mechanical, 21,600 vph, 48-Hour Power Reserve, 21 Jewels",
      "crystal": "Domed Sapphire Crystal with multi-layer interior anti-reflective coating",
      "waterResistance": "5 ATM (50 Meters / 165 Feet)",
      "dial": "Forged carbon fiber & brushed multi-level dial with bat-and-ball small seconds at 5H & 24H AM/PM disc at 9H",
      "strap": "High-durability textured FKM rubber & performance sailcloth hybrid strap with deployant buckle",
      "caseMaterial": "316L Stainless Steel with PVD gunmetal matte finish & chamfered lugs",
      "caseback": "Exhibition sapphire crystal caseback revealing decorated automatic rotor & numbered edition engraving"
    },
    "images": [
      "assets/images/2007_1.jpg",
      "assets/images/2007_2.jpg",
      "assets/images/2007_3.jpg"
    ],
    "limitedEdition": true,
    "editionCount": 100,
    "colorAccent": "#A94B2C",
    "tags": [
      "2007",
      "Automatic Watch",
      "Carbon Fiber Dial",
      "Cricket Watch",
      "Grey Dial",
      "Light Blue Strap",
      "Light Blue Strap Watch",
      "Small Seconds",
      "Sports Watch",
      "Vijay",
      "Watches"
    ]
  },
  {
    "id": 8665236832439,
    "title": "1983",
    "handle": "1983",
    "collection": "Vijay",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "A limited-edition horological tribute commemorating iconic nights of Indian cricketing victory.",
    "editorialBlurb": "Lord\u2019s Cricket Ground, 25 June 1983. The underdog miracle that changed Indian sporting destiny forever. Commemorated in pristine white and brushed carbon.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">The night we first learnt to believe.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">Drawn from the deep navy and crisp whites of India\u2019s earliest victorious era, 1983 captures a moment before colour, spectacle, and superstardom fully took over the game. The restrained palette carries a vintage sporting character:\u00a0<span style=\"mso-spacerun: yes;\">\u00a0</span>disciplined, clean, and quietly defiant.</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">1983 is a tribute to the underdog victory that became an origin story, the night Indian cricket stopped being hopeful and started becoming inevitable.</span></p>\n\n<p><b><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">1983 is a limited edition of 100 pieces only.</span></b></p>\n",
    "specs": {
      "caseSize": "43 mm",
      "thickness": "12.8 mm",
      "lugToLug": "50 mm",
      "lugWidth": "22 mm",
      "movement": "Miyota 82S7 Automatic Mechanical, 21,600 vph, 48-Hour Power Reserve, 21 Jewels",
      "crystal": "Domed Sapphire Crystal with multi-layer interior anti-reflective coating",
      "waterResistance": "5 ATM (50 Meters / 165 Feet)",
      "dial": "Forged carbon fiber & brushed multi-level dial with bat-and-ball small seconds at 5H & 24H AM/PM disc at 9H",
      "strap": "High-durability textured FKM rubber & performance sailcloth hybrid strap with deployant buckle",
      "caseMaterial": "316L Stainless Steel with PVD gunmetal matte finish & chamfered lugs",
      "caseback": "Exhibition sapphire crystal caseback revealing decorated automatic rotor & numbered edition engraving"
    },
    "images": [
      "assets/images/1983_1.jpg",
      "assets/images/1983_2.jpg",
      "assets/images/1983_3.jpg"
    ],
    "limitedEdition": true,
    "editionCount": 100,
    "colorAccent": "#A94B2C",
    "tags": [
      "1983",
      "Automatic Watch",
      "Carbon Fiber Dial",
      "Cricket Watch",
      "Grey Dial",
      "Small Seconds",
      "Sports Watch",
      "Vijay",
      "Watches",
      "White Strap",
      "White Strap Watch"
    ]
  },
  {
    "id": 8665236799671,
    "title": "Kaziranga Gorh",
    "handle": "kaziranga-gorh",
    "collection": "Vanya",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "Field-ready timepieces born from the stillness, tracks, and raw terrain of India\u2019s wildlife sanctuaries.",
    "editorialBlurb": "Wild elephant-grass green dial honoring the great Indian one-horned rhinoceros, with Assamese numeral at 12.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">Built around the slow, ancient power of the one-horned rhinoceros.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">Drawn from Assam\u2019s Riverland, tall elephant grass, and the heavy quiet of the Brahmaputra Valley, Kaziranga Gorh sits in a landscape that feels old, wet, and alive. A deep green fume dial pulls from Kaziranga\u2019s floodplains \u2013 grass darkened by morning dew, forest edges, and river shadows. The black strap with green stitching gives it a sharper, more field-ready edge, like safari gear laid out before sunrise.</span></span><br style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\"></span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">Rhino Hoof Prints move around the dial like heavy impressions in soft earth, hinting at an animal that has never needed to announce its power. Anchored to Assam through its Assamese numeral at 12 and the engraved state map on the caseback,\u00a0</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">Kaziranga Gorh is a tribute to endurance, conservation, and the quiet majesty of a creature that seems to belong to another age.</span><b></b></span></span></p>\n",
    "specs": {
      "caseSize": "40 mm",
      "thickness": "9.8 mm",
      "lugToLug": "47 mm",
      "lugWidth": "20 mm",
      "movement": "Japanese Precision Quartz Movement with central sweep seconds",
      "crystal": "Scratch-resistant Sapphire Crystal",
      "waterResistance": "10 ATM (100 Meters / 330 Feet)",
      "dial": "Topographical dial with animal paw print indices, regional state numeral at 12 & Japanese C3 Super-LumiNova",
      "strap": "Tactical ballistic nylon hook-and-loop velcro strap with reinforced bar-tack stitching",
      "caseMaterial": "316L Stainless Steel with bead-blasted matte anti-glare finish",
      "caseback": "Deep-engraved sanctuary state territory map with individual serial number"
    },
    "images": [
      "assets/images/kaziranga-gorh_1.jpg",
      "assets/images/kaziranga-gorh_2.jpg",
      "assets/images/kaziranga-gorh_3.jpg"
    ],
    "limitedEdition": false,
    "editionCount": null,
    "colorAccent": "#3D5A45",
    "tags": [
      "Assamese Watch",
      "Black Strap",
      "Black Strap Watch",
      "Field Watch",
      "Green Watch",
      "Rhino",
      "Rhino Watch",
      "Vanya",
      "Velcro Strap",
      "Velcro Strap Watch",
      "Watch",
      "Wristwatch"
    ]
  },
  {
    "id": 8665236734135,
    "title": "Jawai Tendua",
    "handle": "jawai-tendua",
    "collection": "Vanya",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "Field-ready timepieces born from the stillness, tracks, and raw terrain of India\u2019s wildlife sanctuaries.",
    "editorialBlurb": "Granite grey textures reflecting the dramatic rocky outcrops where leopards and pastoralists share ancient trails.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">Built around the animal you almost never see coming.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">Drawn from Rajasthan\u2019s granite hills, scrubland and the strange calm of leopard country, Jawai Tendua sits in a landscape where wilderness slips quietly into everyday life. A Dark Grey Fume Dial takes its cue from Jawai\u2019s stone outcrops at dusk: cool, watchful, almost still and the grey strap sharpens it with a nocturnal edge.</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">Leopard Paw Prints cross the dial like soft marks over rock and dust, suggesting an animal defined by stealth rather than spectacle. Anchored to Rajasthan through its Devanagari Numeral at 12 and the engraved state map on the case back, Jawai Tendua is a tribute to coexistence, camouflage, and the charged stillness of a place where the wild lives just beyond the village lights.</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">The most understated watch in the collection because in Jawai, the most powerful presence is often the one you almost miss.</span></span></span></p>\n",
    "specs": {
      "caseSize": "40 mm",
      "thickness": "9.8 mm",
      "lugToLug": "47 mm",
      "lugWidth": "20 mm",
      "movement": "Japanese Precision Quartz Movement with central sweep seconds",
      "crystal": "Scratch-resistant Sapphire Crystal",
      "waterResistance": "10 ATM (100 Meters / 330 Feet)",
      "dial": "Topographical dial with animal paw print indices, regional state numeral at 12 & Japanese C3 Super-LumiNova",
      "strap": "Tactical ballistic nylon hook-and-loop velcro strap with reinforced bar-tack stitching",
      "caseMaterial": "316L Stainless Steel with bead-blasted matte anti-glare finish",
      "caseback": "Deep-engraved sanctuary state territory map with individual serial number"
    },
    "images": [
      "assets/images/jawai-tendua_1.jpg",
      "assets/images/jawai-tendua_2.jpg",
      "assets/images/jawai-tendua_3.jpg"
    ],
    "limitedEdition": false,
    "editionCount": null,
    "colorAccent": "#3D5A45",
    "tags": [
      "Field Watch",
      "Grey Strap",
      "Grey Strap Watch",
      "Grey Watch",
      "Hindi Watch",
      "Leopard",
      "Leopard Watch",
      "Vanya",
      "Velcro Strap",
      "Velcro Strap Watch",
      "Watch",
      "Wristwatch"
    ]
  },
  {
    "id": 8665236701367,
    "title": "Gir Sinh",
    "handle": "gir-sinh",
    "collection": "Vanya",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "Field-ready timepieces born from the stillness, tracks, and raw terrain of India\u2019s wildlife sanctuaries.",
    "editorialBlurb": "Savannah earth brown tones inspired by the Asiatic lion\u2019s last haven. Gujarati numeral at 12 and lion paw indices.",
    "description": "<p style=\"margin-bottom: 0cm; background: white;\"><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\">Drawn from Gujarat\u2019s dry teak forests, thorn scrub and sun-baked trails, Gir Sinh sits in a landscape that feels rugged, open, and quietly powerful. A Warm Brown Fume Dial pulls from Gir\u2019s earth, bark and late-afternoon light, while the brown strap carries the dusty practicality of the forest road.<br style=\"mso-special-character: line-break; box-sizing: border-box;\"><!-- [if !supportLineBreakNewLine]--><br style=\"mso-special-character: line-break; box-sizing: border-box;\"><!--[endif]--></span></p>\n\n<p style=\"margin: 0cm; background: white;\"><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\">Lion Paw Prints move around the dial like heavy marks pressed into dry ground: unhurried, unhidden, and certain. </span></p>\n\n<p style=\"margin: 0cm; background: white;\">\u00a0</p>\n\n<p style=\"margin: 0cm; background: white;\"><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\">Anchored to Gujarat through its Gujarati Numeral at 12 and the engraved state map on the case back, </span><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\">Gir Sinh is a tribute to survival, pride, and the calm confidence of a creature that has never needed to chase attention.</span></p>\n",
    "specs": {
      "caseSize": "40 mm",
      "thickness": "9.8 mm",
      "lugToLug": "47 mm",
      "lugWidth": "20 mm",
      "movement": "Japanese Precision Quartz Movement with central sweep seconds",
      "crystal": "Scratch-resistant Sapphire Crystal",
      "waterResistance": "10 ATM (100 Meters / 330 Feet)",
      "dial": "Topographical dial with animal paw print indices, regional state numeral at 12 & Japanese C3 Super-LumiNova",
      "strap": "Tactical ballistic nylon hook-and-loop velcro strap with reinforced bar-tack stitching",
      "caseMaterial": "316L Stainless Steel with bead-blasted matte anti-glare finish",
      "caseback": "Deep-engraved sanctuary state territory map with individual serial number"
    },
    "images": [
      "assets/images/gir-sinh_1.jpg",
      "assets/images/gir-sinh_2.jpg",
      "assets/images/gir-sinh_3.jpg"
    ],
    "limitedEdition": false,
    "editionCount": null,
    "colorAccent": "#3D5A45",
    "tags": [
      "Brown Strap",
      "Brown Strap Watch",
      "Brown Watch",
      "Field Watch",
      "Gujarati Watch",
      "Lion",
      "Lion Watch",
      "Vanya",
      "Velcro Strap",
      "Velcro Strap Watch",
      "Watch",
      "Wristwatch"
    ]
  },
  {
    "id": 8665236668599,
    "title": "Ranthambore Bagh",
    "handle": "ranthambore-bagh",
    "collection": "Vanya",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "Field-ready timepieces born from the stillness, tracks, and raw terrain of India\u2019s wildlife sanctuaries.",
    "editorialBlurb": "Built around the silence before the sighting in Rajasthan\u2019s dhok scrub. Muted olive dial, paw tracks, and Devanagari 12.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">Built around the silence before the sighting.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">Drawn from Rajasthan\u2019s dry forests, weathered stone forts and the held breath of tiger country, Ranthambore Bagh lives in a landscape where nothing announces itself too early. </span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">A Muted Olive Dial takes its cue from dhok scrub and shadowed trails. The Earthy Brown Strap brings in the dust, bark and trail-worn character of the terrain.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">Tiger Paw Prints circle the dial like signs left on a morning track, hinting at presence rather than revealing it outright. Anchored to Rajasthan through its Devanagari Numeral at 12 and the engraved state map on the case back, Ranthambore Bagh is a tribute to patience, instinct, and that rare moment when the forest suddenly comes alive.</span></span></span></p>\n",
    "specs": {
      "caseSize": "40 mm",
      "thickness": "9.8 mm",
      "lugToLug": "47 mm",
      "lugWidth": "20 mm",
      "movement": "Japanese Precision Quartz Movement with central sweep seconds",
      "crystal": "Scratch-resistant Sapphire Crystal",
      "waterResistance": "10 ATM (100 Meters / 330 Feet)",
      "dial": "Topographical dial with animal paw print indices, regional state numeral at 12 & Japanese C3 Super-LumiNova",
      "strap": "Tactical ballistic nylon hook-and-loop velcro strap with reinforced bar-tack stitching",
      "caseMaterial": "316L Stainless Steel with bead-blasted matte anti-glare finish",
      "caseback": "Deep-engraved sanctuary state territory map with individual serial number"
    },
    "images": [
      "assets/images/ranthambore-bagh_1.jpg",
      "assets/images/ranthambore-bagh_2.jpg",
      "assets/images/ranthambore-bagh_3.jpg"
    ],
    "limitedEdition": false,
    "editionCount": null,
    "colorAccent": "#3D5A45",
    "tags": [
      "Brown Strap",
      "Brown Strap Watch",
      "Field Watch",
      "Green Watch",
      "Hindi Watch",
      "Tiger",
      "Tiger Watch",
      "Vanya",
      "Velcro Strap",
      "Velcro Strap Watch",
      "Watch",
      "Wristwatch"
    ]
  },
  {
    "id": 8665236635831,
    "title": "Rain Check",
    "handle": "rain-check",
    "collection": "Arka",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "Inspired by the Konark Sun Temple sundial geometry, interplay of light and shadow, and time carved in stone.",
    "editorialBlurb": "A rich green sunray dial drawn from a monsoon afternoon, with warm copper-toned Bregnagari numerals and dark brown alligator strap.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; mso-color-alt: windowtext; letter-spacing: .25pt; background: white;\">Nobody\u2019s stepping out for this one.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; letter-spacing: .25pt; background: white;\"></span><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; mso-color-alt: windowtext; letter-spacing: .25pt; background: white;\">The most unhurried expression of the Arka collection: a Rich Green Sunray Dial drawn from a monsoon afternoon, when the garden turns impossibly green and the rain is in no rush to clear. Warm Copper-Toned Bregnagari Numerals sit softly against the green, while the Konark Wheel Small Seconds turns at its own easy pace.</span><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; letter-spacing: .25pt; background: white;\"></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; mso-color-alt: windowtext; letter-spacing: .25pt; background: white;\">A Dark Brown Alligator Textured Calf Leather Strap with subtle stitching keeps it warm, distinctive, and unbothered: made for a good book, a seat by the window, and nowhere else to be.</span><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; letter-spacing: .25pt; background: white;\"></span><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; mso-color-alt: windowtext; letter-spacing: .25pt; background: white;\"></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; mso-color-alt: windowtext; letter-spacing: .25pt; background: white;\">It is not a day lost to the rain.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; mso-color-alt: windowtext; letter-spacing: .25pt; background: white;\">It is a day reclaimed by it.</span><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; letter-spacing: .25pt; background: white;\"></span></p>\n",
    "specs": {
      "caseSize": "38 mm",
      "thickness": "8.5 mm",
      "lugToLug": "45 mm",
      "lugWidth": "20 mm",
      "movement": "Miyota 1L45 Quartz with Konark Wheel Sub-Seconds",
      "crystal": "Sapphire-coated mineral crystal with anti-reflective treatment",
      "waterResistance": "5 ATM (50 Meters / 165 Feet)",
      "dial": "Sunray finish dial with bespoke Bregnagari Devanagari numerals",
      "strap": "20 mm Alligator-embossed genuine Italian calf leather with quick-release bars",
      "caseMaterial": "316L Surgical Grade Stainless Steel, polished bezel & brushed profile",
      "caseback": "Screw-down stainless steel caseback with Konark wheel relief engraving & individual serial number"
    },
    "images": [
      "assets/images/rain-check_1.jpg",
      "assets/images/rain-check_2.jpg",
      "assets/images/rain-check_3.jpg"
    ],
    "limitedEdition": false,
    "editionCount": null,
    "colorAccent": "#8C887F",
    "tags": [
      "Arka",
      "Breganagari",
      "Brown Strap",
      "Brown Strap Watch",
      "Cloud Nine",
      "Dark Green Watch",
      "Devanagari",
      "Dress Watch",
      "Formal Watch",
      "Green Watch",
      "Hindi Numbers",
      "Konark Wheel",
      "Small Seconds",
      "Watch",
      "Wristwatch"
    ]
  },
  {
    "id": 8665236603063,
    "title": "White Noise",
    "handle": "white-noise",
    "collection": "Arka",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "Inspired by the Konark Sun Temple sundial geometry, interplay of light and shadow, and time carved in stone.",
    "editorialBlurb": "An ivory sunray dial built around a steady, unbroken calm, with black Bregnagari numerals and black Konark wheel small seconds.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">The calm of something steady, constant, and quietly always there.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">The most understated expression of the Arka collection is an Ivory Sunray Dial built around a steady, unbroken calm, the visual equivalent of a hum you stop noticing because it never leaves. Black Bregnagari Numerals create a quiet contrast, while a small Black Konark Wheel Small Seconds hand adds depth and rhythm to the dial.</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">A Black Alligator Textured Calf Leather Strap keeps it clean, versatile, and quietly distinctive: a modern Indian dress watch built for the background of every day, not just its highlights.</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">It is not the loudest color in the room.</span></span><br style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">It is the one that's always been right.</span></span></span></p>\n",
    "specs": {
      "caseSize": "38 mm",
      "thickness": "8.5 mm",
      "lugToLug": "45 mm",
      "lugWidth": "20 mm",
      "movement": "Miyota 1L45 Quartz with Konark Wheel Sub-Seconds",
      "crystal": "Sapphire-coated mineral crystal with anti-reflective treatment",
      "waterResistance": "5 ATM (50 Meters / 165 Feet)",
      "dial": "Sunray finish dial with bespoke Bregnagari Devanagari numerals",
      "strap": "20 mm Alligator-embossed genuine Italian calf leather with quick-release bars",
      "caseMaterial": "316L Surgical Grade Stainless Steel, polished bezel & brushed profile",
      "caseback": "Screw-down stainless steel caseback with Konark wheel relief engraving & individual serial number"
    },
    "images": [
      "assets/images/white-noise_1.jpg",
      "assets/images/white-noise_2.jpg",
      "assets/images/white-noise_3.jpg"
    ],
    "limitedEdition": false,
    "editionCount": null,
    "colorAccent": "#8C887F",
    "tags": [
      "Arka",
      "Black Strap",
      "Black Strap Watch",
      "Breganagari",
      "Cloud Nine",
      "Devanagari",
      "Dress Watch",
      "Formal Watch",
      "Hindi Numbers",
      "Konark Wheel",
      "Small Seconds",
      "Watch",
      "White Dial Watch",
      "White Watch",
      "Wristwatch"
    ]
  },
  {
    "id": 8665236570295,
    "title": "After Hours",
    "handle": "after-hours",
    "collection": "Arka",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "Inspired by the Konark Sun Temple sundial geometry, interplay of light and shadow, and time carved in stone.",
    "editorialBlurb": "A deep navy sunray dial drawn from the sky after dark, when the schedule ends but the evening doesn\u2019t. Warm ivory Bregnagari numerals.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">For the hours after the day is officially done, when the city slows but the night is still young.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">The nocturnal expression of the Arka collection: a deep navy sunray dial drawn from the sky after dark, when the schedule ends but the evening doesn't. Warm Ivory Bregnagari Numerals stand crisp against the blue, while the Konark Wheel Small Seconds gives the watch a quiet, continuous rhythm.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">A Black Alligator Textured Calf Leather Strap makes it sharp, cinematic, and easy to dress up: made for dinners that run long, conversations that don't need to end, and the hours that belong to no one but you.</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">It is not the end of the day.</span><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><br style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">It is the part that was always off the clock.</span></span></span></p>\n",
    "specs": {
      "caseSize": "38 mm",
      "thickness": "8.5 mm",
      "lugToLug": "45 mm",
      "lugWidth": "20 mm",
      "movement": "Miyota 1L45 Quartz with Konark Wheel Sub-Seconds",
      "crystal": "Sapphire-coated mineral crystal with anti-reflective treatment",
      "waterResistance": "5 ATM (50 Meters / 165 Feet)",
      "dial": "Sunray finish dial with bespoke Bregnagari Devanagari numerals",
      "strap": "20 mm Alligator-embossed genuine Italian calf leather with quick-release bars",
      "caseMaterial": "316L Surgical Grade Stainless Steel, polished bezel & brushed profile",
      "caseback": "Screw-down stainless steel caseback with Konark wheel relief engraving & individual serial number"
    },
    "images": [
      "assets/images/after-hours_1.jpg",
      "assets/images/after-hours_2.jpg",
      "assets/images/after-hours_3.jpg"
    ],
    "limitedEdition": false,
    "editionCount": null,
    "colorAccent": "#8C887F",
    "tags": [
      "Arka",
      "Black Strap",
      "Black Strap Watch",
      "Blue Watch",
      "Breganagari",
      "Cloud Nine",
      "Devanagari",
      "Dress Watch",
      "Formal Watch",
      "Hindi Numbers",
      "Konark Wheel",
      "Navy Blue Watch",
      "Small Seconds",
      "Watch",
      "Wristwatch"
    ]
  },
  {
    "id": 8665236537527,
    "title": "Golden Hour",
    "handle": "golden-hour",
    "collection": "Arka",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "Inspired by the Konark Sun Temple sundial geometry, interplay of light and shadow, and time carved in stone.",
    "editorialBlurb": "A warm salmon sunray dial drawn from evening light as it falls across stone, skin, and sky, paired with deep blue Bregnagari numerals.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">The hour when the day turns warm, soft, and golden.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">The most radiant expression of the Arka collection is a warm Salmon Sunray Dial drawn from evening light as it falls across stone, skin, and sky. Deep Blue Bregnagari Numerals bring a crisp contrast to the dial, while the Konark Wheel Small Seconds adds a quiet pulse to the composition.</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">A Dark Brown Alligator Textured Calf Leather Strap keeps it elegant but not formal, warm but not loud, made for golden hours, long evenings, and moments that deserve to stretch a little longer.</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">It is not just the colour of the sunset.</span></span><br style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">It is the glow before the day lets go.</span></span></span></p>\n",
    "specs": {
      "caseSize": "38 mm",
      "thickness": "8.5 mm",
      "lugToLug": "45 mm",
      "lugWidth": "20 mm",
      "movement": "Miyota 1L45 Quartz with Konark Wheel Sub-Seconds",
      "crystal": "Sapphire-coated mineral crystal with anti-reflective treatment",
      "waterResistance": "5 ATM (50 Meters / 165 Feet)",
      "dial": "Sunray finish dial with bespoke Bregnagari Devanagari numerals",
      "strap": "20 mm Alligator-embossed genuine Italian calf leather with quick-release bars",
      "caseMaterial": "316L Surgical Grade Stainless Steel, polished bezel & brushed profile",
      "caseback": "Screw-down stainless steel caseback with Konark wheel relief engraving & individual serial number"
    },
    "images": [
      "assets/images/golden-hour_1.jpg",
      "assets/images/golden-hour_2.jpg",
      "assets/images/golden-hour_3.jpg"
    ],
    "limitedEdition": false,
    "editionCount": null,
    "colorAccent": "#8C887F",
    "tags": [
      "Arka",
      "Breganagari",
      "Brown Strap",
      "Brown Strap Watch",
      "Cloud Nine",
      "Devanagari",
      "Dress Watch",
      "Formal Watch",
      "Hindi Numbers",
      "Konark Wheel",
      "Pink Watch",
      "Salmon Watch",
      "Small Seconds",
      "Watch",
      "Wristwatch"
    ]
  },
  {
    "id": 8665236504759,
    "title": "Cloud Nine",
    "handle": "cloud-nine",
    "collection": "Arka",
    "price": 9999,
    "priceFormatted": "\u20b99,999",
    "tagline": "Inspired by the Konark Sun Temple sundial geometry, interplay of light and shadow, and time carved in stone.",
    "editorialBlurb": "A powder blue sunray dial that feels like morning skies and good moods, drawn from the softest hour of the day with deep blue Bregnagari numerals.",
    "description": "<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">The feeling of being exactly where you want to be.</span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">The airiest expression of the Arka collection: a powder blue sunray dial that feels like morning skies and good moods, drawn from the softest hour of the day. Deep Blue Bregnagari Numerals lend it contrast and character, while the Konark Wheel at 6 o'clock brings a gentle, turning rhythm to the dial.</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">A Navy Blue Alligator Textured Calf Leather Strap with subtle Blue Stitching keeps it light, easy, and quietly joyful, a dress watch that feels like a good day ahead.</span></span></span></p>\n\n<p><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt; background: white;\">It is not about staying grounded.</span><span style=\"font-size: 10.5pt; font-family: 'Arial',sans-serif; color: black; letter-spacing: .25pt;\"><br style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;\"><span style=\"background: white;\"><span style=\"font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; float: none; word-spacing: 0px;\">It is about floating a little higher</span>.</span></span></p>\n",
    "specs": {
      "caseSize": "38 mm",
      "thickness": "8.5 mm",
      "lugToLug": "45 mm",
      "lugWidth": "20 mm",
      "movement": "Miyota 1L45 Quartz with Konark Wheel Sub-Seconds",
      "crystal": "Sapphire-coated mineral crystal with anti-reflective treatment",
      "waterResistance": "5 ATM (50 Meters / 165 Feet)",
      "dial": "Sunray finish dial with bespoke Bregnagari Devanagari numerals",
      "strap": "20 mm Alligator-embossed genuine Italian calf leather with quick-release bars",
      "caseMaterial": "316L Surgical Grade Stainless Steel, polished bezel & brushed profile",
      "caseback": "Screw-down stainless steel caseback with Konark wheel relief engraving & individual serial number"
    },
    "images": [
      "assets/images/cloud-nine_1.jpg",
      "assets/images/cloud-nine_2.jpg",
      "assets/images/cloud-nine_3.jpg"
    ],
    "limitedEdition": false,
    "editionCount": null,
    "colorAccent": "#8C887F",
    "tags": [
      "Arka",
      "Blue Strap",
      "Blue Strap Watch",
      "Blue Watch",
      "Breganagari",
      "Cloud Nine",
      "Devanagari",
      "Dress Watch",
      "Formal Watch",
      "Hindi Numbers",
      "Konark Wheel",
      "Light Blue Watch",
      "Small Seconds",
      "Watch",
      "Wristwatch"
    ]
  }
];

export const COLLECTIONS = {
  arka: {
    name: "ARKA",
    theme: "Light, Shadow & Stone Sundials",
    inspiration: "Inspired by the Konark Sun Temple sundial geometry, interplay of light and shadow, and time carved in stone.",
    headline: "Time Carved in Stone & Light",
    priceStarting: "₹9,999",
    badge: "Core Dress Series",
    color: "#EFEBE4",
    heroWatch: "after-hours",
    heroImg: "assets/images/after-hours_1.jpg"
  },
  vanya: {
    name: "VANYA",
    theme: "Untamed Indian Sanctuaries",
    inspiration: "Field-ready timepieces born from the stillness, tracks, and raw terrain of India’s wildlife sanctuaries.",
    headline: "Built for the Silence Before the Sighting",
    priceStarting: "₹9,999",
    badge: "Field & Adventure Series",
    color: "#2A362E",
    heroWatch: "ranthambore-bagh",
    heroImg: "assets/images/ranthambore-bagh_1.jpg"
  },
  vijay: {
    name: "VIJAY",
    theme: "Nights of Victory & Legacy",
    inspiration: "A limited-edition automatic tribute commemorating landmark nights of Indian cricketing glory (1983, 2007, 2011, 2024, 2026).",
    headline: "When Victory Becomes Legacy",
    priceStarting: "₹19,470",
    badge: "Limited Edition (100 Pcs)",
    color: "#181E27",
    heroWatch: "1983",
    heroImg: "assets/images/1983_1.jpg"
  }
};
